# Copyright 2019 IBM Corporation
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loyalty-level
  labels: 
    solution: stock-trader
    kappnav.action.metrics.mp20: "true"
  annotations:
    kappnav.subkind: Liberty
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loyalty-level
        version: v1
        appview: stock-trader
    spec:
      containers:
      - name: loyalty-level
        image: docker.io/kappnav/sample-liberty:latest
        imagePullPolicy: Always
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: loyalty-level-service
  labels:
    app: loyalty-level
    solution: stock-trader
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: loyalty-level
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: loyalty-level-monitor
  name: loyalty-level-monitor
  namespace: stocktrader
spec:
  endpoints:
    - interval: 30s
      tlsConfig:
        insecureSkipVerify: true
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - stocktrader
  selector:
    matchLabels:
      app: loyalty-level
